# traefik.yaml

# Enable Docker provider
providers:
  docker:
    endpoint: "tcp://docker-proxy:2375" # Enable for Socket Proxy. Disable otherwise.
    exposedByDefault: false
    network: "homelab_traefik_bridge"
  file:
    directory: "/config/dynamic" # Load dynamic configuration from one or more .toml or .yml files in a directory
    watch: true # Only works on top-level files in the rules folder
# EntryPoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: dns-cloudflare
        options: tls-opts@file
        domains:
          - main: "chalk-ho.me"
            sans:
              - "*.chalk-ho.me"
    forwardedHeaders:
      trustedIPs:
        # {{ CLOUDFLARE_IPS }} #
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 127.0.0.1/32
        - 100.64.0.0/10
        - fd7a:115c:a1e0::/48
        - 10.0.11.0/24
        - 10.2.0.0/23
        - 10.2.2.0/23
        - 10.2.4.0/23
api:
  dashboard: true
ping: {}
# Logging
log:
  filePath: "/logs/traefik.log"
  level: "INFO"
accessLog:
  filePath: "/logs/access.log"
  addInternals: false
  bufferingSize: 100
  filters:
    statusCodes:
      - 204-299
      - 400-499
      - 500-599
# Certificates Resolvers
certificatesResolvers:
  dns-cloudflare:
    acme:
      storage: "/acme.json"
      dnsChallenge:
        provider: "cloudflare"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
        delayBeforeCheck: "90" # To delay DNS check and reduce LE hit rate
