version: "3"
vars:
  LOG_DIR: "/home/docker/homelab/logs"
  DATA_DIR: "/home/docker/homelab/data"
  SECRETS_DIR: "/home/docker/homelab/secrets"
  APPS_DIR: "/home/docker/homelab/apps"
env:
  DATA_DIR: "{{.DATA_DIR}}"
  LOG_DIR: "{{.LOG_DIR}}"
  SECRETS_DIR: "{{.SECRETS_DIR}}"
dotenv: ["./.env"]
includes:
  compose:
    taskfile: taskfiles/DockerCompose.yaml
    aliases:
      - docker-compose
  photos-library:
    taskfile: taskfiles/PhotoLibrary.yaml
    aliases:
      - photos-lib
      - photos
