version: "3"
vars:
  LOGDIR: "/home/chalk.linux/workspace/logs"
  DATADIR: "/home/chalk.linux/workspace/data"
  SECRETSDIR: "/home/chalk.linux/workspace/secrets"
  APPS_DIR: "/home/chalk.linux/workspace/apps"
env:
  DATADIR: "{{.DATADIR}}"
  LOGDIR: "{{.LOGDIR}}"
  SECRETSDIR: "{{.SECRETSDIR}}"
dotenv: ["./.env"]
includes:
  compose:
    taskfile: taskfiles/DockerCompose.yaml
    aliases:
      - docker-compose
  photos-library:
    taskfile: taskfiles/PhotoLibrary.yaml
    aliases:
      - photos-lib
      - photos
