version: "3"
vars:
  PROJECT_ROOT: "$PROJECT_ROOT"
  SECRETSPATH: "$SECRETSPATH"
  APPSPATH: "$APPSPATH"
  STORAGE_ROOT: "$STORAGE_ROOT"
  DATAPATH: "$DATAPATH"
  LOGSPATH: "$LOGSPATH"
dotenv: ["./.env"]
includes:
  compose:
    taskfile: taskfiles/DockerCompose.yaml
    aliases:
      - docker-compose
  photos-library:
    taskfile: taskfiles/PhotoLibrary.yaml
    aliases:
      - photos-lib
      - photos
