services:
  exitnode-tailscale:
    image: tailscale/tailscale:latest
    container_name: exitnode-tailscale
    user: root
    profiles: ["vpn", "all"]
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - default
    volumes:
      - "$DATADIR/exitnode/tailscale/state:/var/lib/tailscale"
      - "./scripts:/scripts"
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always
    command: ['/scripts/tailscale_up.sh']
  exitnode-nordvpn:
    build:
      context: nordvpn
    container_name: exitnode-nordvpn
    profiles: ["vpn", "all"]
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    hostname: exitnode-nordvpn
    networks:
      default:
        ipv4_address: 10.2.0.30
    volumes:
      - "/dev/net/tun:/dev/net/tun"
      - "./scripts:/scripts"
    restart: always
    entrypoint: ['/scripts/nordvpn_up.sh']
