services:
  # CrowdSec - Open-source & collaborative security IPS
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    profiles: ["security", "core", "all"]
    security_opt:
      - no-new-privileges:true
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux
      CUSTOM_HOSTNAME: lima-default
      GID: ${PGID-1000}
    networks:
      - default
    ports:
      - "8080:8080" # Local API port
    volumes:
      # - $RUN_DIR/logs/cloudserver:/logs/cloudserver:ro
      - $LOG_DIR:/logs:ro
      - /var/log:/var/log:ro
      # - $EXTDRIVE/zbox/var/log:/logs/zbox:ro
      - crowdsec-data:/var/lib/crowdsec/data
      - $DATA_DIR/crowdsec:/etc/crowdsec
    depends_on:
      - traefik
    restart: unless-stopped
volumes:
  crowdsec-data:
