services:
  # AdGuard Home - DNS AdBlocking
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    profiles: ["core", "all", "dns"]
    networks:
      - traefik
    ports:
      - 0.0.0.0:53:53/tcp
      - 0.0.0.0:53:53/udp
      - 0.0.0.0:853:853/tcp
      - 0.0.0.0:784:784/udp
      - 0.0.0.0:853:853/udp
      - 0.0.0.0:8853:8853/udp
      - 0.0.0.0:5443:5443/tcp
      - 0.0.0.0:5443:5443/udp
    volumes:
      - $DATADIR/adguardhome/conf:/opt/adguardhome/conf
      - $DATADIR/adguardhome/work:/opt/adguardhome/work
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguardhome-rtr.entrypoints=websecure
      - traefik.http.routers.adguardhome-rtr.rule=Host(`dns.$BASE_DOMAIN`)
      - traefik.http.routers.adguardhome-rtr.middlewares=chain-no-auth@file
      - traefik.http.services.adguardhome-svc.loadbalancer.server.port=80
      - traefik.http.routers.adguardhome-rtr.service=adguardhome-svc
      # - "traefik.tcp.routers.adguardhome-tls-rtr.service=adguardhome-tls-svc"
