services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    profiles: ["base"]
    environment:
      - "TZ=Asia/Seoul"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    volumes:
      - "$DATAPATH/diun/data:/data"
      - "$DATAPATH/diun/diun.yaml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    command: serve
