services:
  error-pages:
    image: tarampampam/error-pages:3.2
    container_name: error-pages
    profiles: ["core", "all"]
    environment:
      TEMPLATE_NAME: connection
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=$TRAEFIK_BRIDGE
      - traefik.http.routers.error-pages-rtr.entrypoints=websecure
      - traefik.http.routers.error-pages-rtr.tls=true
      - traefik.http.routers.error-pages-rtr.rule=HostRegexp(`.+`)
      - traefik.http.routers.error-pages-rtr.priority=10
      - traefik.http.routers.error-pages-rtr.middlewares=rule-error-pages
      - traefik.http.services.error-pages-svc.loadbalancer.server.port=8080
      - traefik.http.middlewares.rule-error-pages.errors.status=400-599
      - traefik.http.middlewares.rule-error-pages.errors.service=error-pages-svc
      - traefik.http.middlewares.rule-error-pages.errors.query=/{status}.html
