volumes:
  tsdproxy-data:
secrets:
  tsdproxy_tailscale_authkey:
    file: $SECRETSPATH/tsdproxy_tailscale_authkey
#     - TS_ROUTES=10.2.0.0/16
#     network_mode: host
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    profiles: ["base"]
    privileged: true
    secrets:
      - tsdproxy_tailscale_authkey
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy-data:/data
      - $DATAPATH/tsdproxy:/config
    restart: unless-stopped
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=dashboard"
      - "tsdproxy.ephemeral=true"
