services:
  # pgAdmin - PostgreSQL Administration
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    profiles: ["apps", "all"]
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    networks:
      - traefik
      - default
    # ports:
    #   - "$PGADMIN_PORT:80"
    volumes:
      - pgadmin-PROJECT_ROOT:/var/lib/pgadmin
      - $DATAPATH/pgadmin/config_local.py:/pgadmin4/config_local.py
    restart: unless-stopped
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=pgadmin"
      - "tsdproxy.container_port=80"
      - "tsdproxy.ephemeral=true"
      - "traefik.enable=true"
      - "traefik.docker.network=$TRAEFIK_BRIDGE"
      # HTTP Routers
      - "traefik.http.routers.pgadmin-rtr.entrypoints=websecure"
      - "traefik.http.routers.pgadmin-rtr.rule=Host(`pgadmin.$BASE_DOMAIN`)"
      # Middlewares
      - "traefik.http.routers.pgadmin-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.pgadmin-rtr.service=pgadmin-svc"
      - "traefik.http.services.pgadmin-svc.loadbalancer.server.port=80"
volumes:
  pgadmin-PROJECT_ROOT:
