services:
  # HomeAssistant
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    profiles: ["apps", "all"]
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    environment:
      - PUID
      - PGID
    network_mode: host
    volumes:
      # Local path where your home assistant config will be stored
      - $DATADIR/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    depends_on:
      - timescaledb
      - zigbee2mqtt
      - emqx
    restart: unless-stopped
    healthcheck:
      interval: 30s
      retries: "10"
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8123"]
      timeout: 10s
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=hass
      - tsdproxy.container_port=8123
      - tsdproxy.ephemeral=true
