services:
  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  docker-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: docker-proxy
    profiles: ["core", "all"]
    privileged: true
    security_opt:
      - no-new-privileges:true
    environment:
      - LOG_LEVEL=warning
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      ## Granted by default
      - EVENTS=1
      # Revoked by default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
      - DISABLE_IPV6=0
    networks:
      - default
    # ports:
    #- "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
