services:
  # Cloudflared - Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    profiles: ["core", "all"]
    networks:
      - external
      - traefik
    environment:
      - PUID
      - PGID
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $DATADIR/cloudflared:/etc/cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yaml run
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
