credentials-file: /etc/cloudflared/credentials.json
ingress:
  - service: https://traefik:443
originRequest:
  noTLSVerify: true
  originServerName: chalk-ho.me
tunnel: 73179ee3-e36f-43ba-b9d0-18f4d16c5578
