type: trigger
format: 2.0
name: crowdsecurity/CVE-2024-9474
description: "Detect CVE-2024-9474 exploitation attempts"
filter: "let request = Lower(evt.Parsed.request);\nevt.Meta.log_type in ['http_access-log', 'http_error-log'] && \nevt.Meta.http_status in ['404', '403'] &&\nevt.Meta.http_verb == 'POST' &&\nrequest contains '/php/utils/createremoteappwebsession.php/watchtowr.js.map'\n"
groupby: "evt.Meta.source_ip"
blackhole: 2m
labels:
  type: exploit
  remediation: true
  classification:
    - attack.T1595
    - attack.T1190
    - cve.CVE-2024-9474
  confidence: 3
  spoofable: 0
  behavior: "http:exploit"
  label: "CVE-2024-9474"
  service: panos
