volumes:
  redis-data:
services:
  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    ports:
      - "6379:6379"
    networks:
      - default
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - $DATAPATH/redis/data:/data
      - $DATAPATH/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro