volumes:
  redis-data:
services:
  # Redis - Key-value Store
  redis:
    user: $PUID:$PGID
    container_name: redis
    image: redis:latest
    security_opt:
      - no-new-privileges:true
    sysctls:
      - vm.overcommit_memory=1
    restart: unless-stopped
    profiles: ["core", "all"]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - default
    entrypoint: redis-server --appendonly yes --requirepass $REDIS_PASSWORD --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro